env:
  es6: true
  browser: true
  commonjs: true

extends: ["eslint:recommended", "plugin:react/recommended"]

parserOptions:
  ecmaFeatures:
    jsx: true
  ecmaVersion: 2021
  sourceType: module

plugins: ["react", "react-hooks"]

settings:
  react:
    version: "17"

rules:
  react-hooks/rules-of-hooks: "error"
  react-hooks/exhaustive-deps: "warn"
  react/jsx-uses-react: "off"
  react/react-in-jsx-scope: "off"
  no-unused-vars:
    - error
    -
      argsIgnorePattern: "^_"
