export const ActionTypes = {
  SET_TOTAL_COUNT: 'SET_TOTAL_COUNT',
  SET_COUNTERS: 'SET_COUNTERS',
  ADD_COUNTER: 'ADD_COUNTER',
  REMOVE_COUNTER: 'REMOVE_COUNTER',
  DECREMENT_COUNTER: 'DECREMENT_COUNTER',
  INCREMENT_COUNTER: 'INCREMENT_COUNTER',
};

export const InitialValues = {
  TOTAL_COUNT: 0,
  COUNTERS: [],
};
