export const ActionTypes = {
  SET_FAVORITES_REQUEST: 'SET_FAVORITES_REQUEST',
  SET_FAVORITES_SUCCESS: 'SET_FAVORITES_SUCCESS',
  SET_FAVORITES_ERROR: 'SET_FAVORITES_ERROR',
  FETCH_FAVORITES: 'FETCH_FAVORITES',
  ADD_TO_FAVORITES_IDS: 'ADD_TO_FAVORITES_IDS',
  REMOVE_FROM_FAVORITES: 'REMOVE_FROM_FAVORITES',
  UPDATE_FAVORITES: 'UPDATE_FAVORITES',
};

export const InitialValues = {
  FAVORITES_IDS_ALL_USERS: {},
  FAVORITES_IDS: [],
  FAVORITES: [],
  IS_LOADED: false,
  ERROR_MSG: null,
};
